#!/bin/bash
for entry in $(echo $WEBAPPSLIST); do
    name="${entry%%|*}"
    url="${entry#*|}"
cat << EOF | tee $APPDIR/$name
#!/bin/bash
google-chrome-stable --app="${url}"
EOF

cat << EOF | tee $SHORTCUTDIR/$name.desktop
[Desktop Entry]
Name=$name
Exec=$name
Icon=google-chrome
Terminal=false
Type=Application
Categories=Network;
EOF

chmod 755 $APPDIR/$name
done