#!/bin/bash

WEBAPPSLIST=$1
APPDIR=$2

for entry in "${WEBAPPSLIST[@]}"; do
    name="${entry%%|*}"
    url="${entry#*|}"
cat << EOF | tee $APPDIR/$name
#!/bin/bash
google-chrome-stable --app="${url}"
EOF
chmod 755 $APPDIR/$name
done