#!/bin/bash
export REMOTE_CLUSTER_HOST=$1

if [ -z "$REMOTE_CLUSTER_HOST" ]; then
    echo "Error: REMOTE_CLUSTER_HOST is required" >&2
    exit 1
fi

mkdir -p ~/.kube/
scp $REMOTE_CLUSTER_HOST:~/.kube/config ~/.kube/config
K8S_PUBLIC_DOMAIN=$(ssh $REMOTE_CLUSTER_HOST 'bash -i -c "echo \$K3S_WILDCARD_DOMAIN" 2>/dev/null')
OLD_CLUSTER=$(kubectl config view --kubeconfig ~/.kube/config -o jsonpath='{.clusters[0].name}')
OLD_CONTEXT=$(kubectl config view --kubeconfig ~/.kube/config -o jsonpath='{.contexts[0].name}')
sed -i "s|server: https://.*|server: https://$REMOTE_CLUSTER_HOST:6443|g" ~/.kube/config
sed -i "/^clusters:/,/^contexts:/s|name: $OLD_CLUSTER$|name: $K8S_PUBLIC_DOMAIN|" ~/.kube/config
sed -i "s|cluster: $OLD_CLUSTER$|cluster: $K8S_PUBLIC_DOMAIN|g" ~/.kube/config
kubectl config rename-context "$OLD_CONTEXT" "$K8S_PUBLIC_DOMAIN" --kubeconfig ~/.kube/config
