#!/bin/bash

wget -O /tmp/oteldemo.yaml https://raw.githubusercontent.com/alainpham/dotfiles/master/scripts/kube/otel/oteldemo.yaml
envsubst '${GCLOUD_FARO}' < /tmp/oteldemo.yaml | kubectl apply -n otel-demo -f -
 


wget -O /tmp/expose.yaml https://raw.githubusercontent.com/alainpham/dotfiles/master/scripts/kube/otel/expose.yaml
envsubst < /tmp/expose.yaml | kubectl apply -n otel-demo -f -

