#!/bin/bash
export REMOTE_CLUSTER_HOST=$1

if [ -z "$REMOTE_CLUSTER_HOST" ]; then
    echo "Error: REMOTE_CLUSTER_HOST is required" >&2
    exit 1
fi

mkdir -p ~/.kube/
scp $REMOTE_CLUSTER_HOST:~/.kube/config ~/.kube/config
K8S_PUBLIC_DOMAIN=$(ssh $REMOTE_CLUSTER_HOST 'bash -i -c "echo \$K3S_WILDCARD_DOMAIN" 2>/dev/null')
OLD_NAME=$(kubectl config view --kubeconfig ~/.kube/config -o jsonpath='{.clusters[0].name}')
sed -i "s|server: https://.*|server: https://$REMOTE_CLUSTER_HOST:6443|g" ~/.kube/config
sed -i "s/: $OLD_NAME$/: $K8S_PUBLIC_DOMAIN/g" ~/.kube/config
