node.rules = [
  {
    matches = [
      { node.name = "OBS Studio: 01-02-dtop" }
    ]
    actions = {
      update-props = {
        target.object = "from-desktop"
        node.dont-reconnect = false
      }
    }
  }
  {
    matches = [
      { node.name = "OBS Studio: 01-03-clr" }
    ]
    actions = {
      update-props = {
        target.object = "from-caller"
        node.dont-reconnect = false
      }
    }
  }
]
