wireplumber.settings = {
  default.audio.sink = "from-desktop"
  default.audio.source = "mic01-processed"
  bluetooth.autoswitch-to-headset-profile = false
  bluetooth.profile-switching = false
  device.restore-profile = false
}