monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.loop" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  },
  {
    matches = [
      { device.name = "alsa_card.dummy" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  },
  {
    matches = [
      { device.name = "~alsa_card.*C920.*" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]