#!/bin/bash

imageurl=https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2

mkdir -p /home/$USER/virt/images/
if [[ ! -f /home/$USER/virt/images/lnsv-orig.qcow2 ]] || [[ "$1" == "1" ]]; then
    curl -Lo /home/$USER/virt/images/lnsv-orig.qcow2 $imageurl
fi

vmcr bast 1024 4 lnsv-orig 50 80G generic