#!/bin/bash

imageurl=https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
mkdir -p /home/$USER/virt/images/

if [[ ! -f /home/$USER/virt/images/lnsvr-orig.img ]] || [[ "$1" == "1" ]]; then
    curl -Lo /home/$USER/virt/images/lnsvr-orig.img $imageurl
fi

vmcr bast 1024 4 lnsvr $ipaddrsuffix 80G 1G ubuntu24.04