#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 <hostname> <number 10-99>" >&2
  exit 1
fi

if ! echo "$1" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$'; then
  echo "Error: '$1' is not a valid hostname" >&2
  exit 1
fi

if ! echo "$2" | grep -qE '^[0-9]+$' || [ "$2" -lt 10 ] || [ "$2" -gt 99 ]; then
  echo "Error: '$2' must be a number between 10 and 99" >&2
  exit 1
fi

MAC="52:54:00:00:00:$2"
IP="192.168.122.$2"
VMS_DIR=/home/${USER}/virt/runtime
virsh net-update default add ip-dhcp-host "<host mac='$MAC' name='$1' ip='$IP' />" --live --config
lineinfile "/etc/NetworkManager/dnsmasq.d/vms" ".address=.$1" "address=/$1/$IP"
nmcli general reload