gesture swipe up        xdotool key super+m
gesture swipe down      xdotool key super+t
gesture swipe left      3 xdotool key alt+Left
gesture swipe left      4 xdotool key super+Left
gesture swipe right     3 xdotool key alt+Right
gesture swipe right     4 xdotool key super+Right