#!/bin/bash
csnddmy

CARD=$(pactl list short cards | grep bluez_card | awk '{print $2}')
sndprofile=$(
    pactl -f json list cards | jq -r --arg CARD "$CARD" '
        .[]
        | select(.name == $CARD)
        | .profiles
        | keys[]' | grep ^a2dp.sink$
)
pactl set-card-profile "$CARD" "$sndprofile"

source $(which asndenv)

speakers=$btfspeakerid
mic=$btfmicid
speakervolume=$btfspeakervolume
micvolume=$btfmicvolume

asnd $speakers $mic $speakervolume $micvolume
