#!/bin/bash
server_name=$(pactl info | grep "Server Name")
if echo "$server_name" | grep -qi "pipewire"; then
    svr="pw"
elif echo "$server_name" | grep -qi "pulseaudio"; then
    svr="pa"
    csnddmy
else
    exit 1
fi

CARD=$(pactl list short cards | grep bluez_card | awk '{print $2}')
sndprofile=$(
    pactl -f json list cards | jq -r --arg CARD "$CARD" '
        .[]
        | select(.name == $CARD)
        | .profiles
        | keys[]' | grep ^a2dp.sink$
)
pactl set-card-profile "$CARD" "$sndprofile"
source $(which asndenv)

speakers=$btfspeakerid
mic=$btfmicid
speakervolume=$btfspeakervolume
micvolume=$btfmicvolume

asnd $speakers $mic $speakervolume $micvolume
