#!/bin/bash
csnddmy

CARD=$(pactl list short cards | grep bluez_card | awk '{print $2}')
sndprofile=$(
    pactl -f json list cards | jq -r --arg CARD "$CARD" '
        .[]
        | select(.name == $CARD)
        | .profiles
        | keys[]' | grep ^a2dp.sink$
)
pactl set-card-profile "$CARD" "$sndprofile"
source $(which asndenv)

speakers=$bthspeakerid
mic=$bthmicid
speakervolume=$bthspeakervolume
micvolume=$bthmicvolume

asnd $speakers $mic $speakervolume $micvolume
sleep 1

asnd $speakers $mic $speakervolume $micvolume
