Net/ThemeName "${GTK_THEME}"
Net/IconThemeName "${GTK_ICON_THEME}"
Gtk/CursorThemeName "${GTK_CURSOR_THEME}"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintmedium"
Xft/RGBA "rgb"
