#!/bin/bash
eval $(xdotool getmouselocation --shell)

geom=$(xrandr | awk -v x=$X -v y=$Y '
/ connected/ {
  for (i=1; i<=NF; i++) {
    if ($i ~ /^[0-9]+x[0-9]+\+[0-9]+\+[0-9]+$/) {
      split($i,a,"[x+]")
      if (x>=a[3] && x<a[3]+a[1] && y>=a[4] && y<a[4]+a[2]) {
        print $i
        exit
      }
    }
  }
}')

[ -n "$geom" ] && maim -g "$geom" | xclip -selection clipboard -t image/png