#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
preset=${2:-faster}
crf=${3:-23}
maxrate=${4:-4320}
ab=${5:-160}
format=${6:-mp4}

ffmpeg -y \
    -i $1 \
    -f ${format} \
        -preset ${preset} \
        -pix_fmt yuv420p \
        -c:v libx264 \
        -crf ${crf} \
        -bufsize ${maxrate}k \
        -maxrate ${maxrate}k \
        -c:a libfdk_aac \
        -b:a ${ab}k \
        -movflags +faststart \
        ${filename}-x264-crf${crf}-maxrate${maxrate}k-fdk_aac-ab${ab}k.${format}
