#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
preset=${2:-slow}
crf=${3:-23}
ab=${4:-160}
format=${5:-mp4}

ffmpeg -y \
    -i $1 \
    -f ${format} \
        -preset slow \
        -pix_fmt yuv420p \
        -c:v libx264 \
        -crf ${crf} \
        -bufsize 16384k \
        -maxrate 16384k \
        -c:a libfdk_aac \
        -b:a ${ab}k \
        -movflags +faststart \
        ${filename}-x264-crf${crf}-fdk_aac-ab${ab}k.${format}
