#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
#1080p 4096k
#720p  1888k
preset=${2:-faster}
bitrate=${3:-1184}
ab=${4:-96}
format=${5:-mp4}
width=${6:-1280}

maxrate=$((($ab + $bitrate) * 4))
# main profile level 4.0 for max compat
if [ $maxrate -gt 19808 ]; then
    maxrate=19808
fi

# pass 1
ffmpeg -y \
    -i "$1" \
    -f ${format} \
        -preset $preset \
        -pix_fmt yuv420p \
        -vf scale=${width}:-2 \
        -c:v libx264 \
        -b:v ${bitrate}k  \
        -bufsize ${maxrate}k \
        -maxrate ${maxrate}k \
        -pass 1 \
        -an \
        /dev/null

# pass 2
ffmpeg \
    -i "$1" \
    -f ${format} \
        -preset $preset \
        -pix_fmt yuv420p \
        -vf scale=${width}:-2 \
        -c:v libx264 \
        -b:v ${bitrate}k  \
        -bufsize ${maxrate}k \
        -maxrate ${maxrate}k \
        -pass 2 \
        -c:a libfdk_aac \
        -b:a ${ab}k \
        -movflags +faststart \
        "${filename}-x264-720p-vbr${bitrate}k-faac-ab${ab}k.${format}"
