#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
bitrate=${2:-3936}
ab=${3:-320}
format=${4:-mp4}

ffmpeg -y \
    -vaapi_device /dev/dri/renderD128 \
    -i "$1" \
    -f ${format} \
        -vf 'format=nv12|vaapi,hwupload' \
        -c:v h264_vaapi \
        -b:v ${bitrate}k
        -c:a libfdk_aac \
        -ab ${ab}k \
        ${filename}-h264-vaapi-qp${qp}-faac-ab${ab}k.${format}
