#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
#1080p 4096k
#720p  2264k
bitrate=${2:-3936}
ab=${3:-160}
format=${4:-mp4}

maxrate=$((($ab + $bitrate) * 4))
# main profile level 4.0 for max compat
if [ $maxrate -gt 19456 ]; then
    maxrate=19456
fi



ffmpeg -y \
    -i $1 \
    -f ${format} \
        -preset slow \
        -pix_fmt yuv420p \
        -c:v libx264 \
        -b:v ${bitrate}k  \
        -bufsize ${maxrate}k \
        -maxrate ${maxrate}k \
        -pass 1 \
        -an \
        /dev/null

ffmpeg \
    -i $1 \
    -f ${format} \
        -preset slow \
        -pix_fmt yuv420p \
        -c:v libx264 \
        -b:v ${bitrate}k  \
        -bufsize ${maxrate}k \
        -maxrate ${maxrate}k \
        -pass 2 \
        -c:a libfdk_aac \
        -b:a ${ab}k \
        -movflags +faststart \
        ${filename}-x264-vbr${bitrate}k-aac-ab${ab}k.${format}
