#!/bin/bash
extension="${1##*.}"
filename="${1%.*}"
#extreme visually lossess at qp=14
qp=${2:-14}
format=${4:-mkv}

ffmpeg -y \
    -vaapi_device /dev/dri/renderD128 \
    -i "$1" \
    -f ${format} \
        -vf 'format=nv12|vaapi,hwupload' \
        -c:v h264_vaapi \
        -qp ${qp} \
        -c:a copy
        ${filename}-h264-vaapi-qp${qp}-master.${format}
