[env]
TERM = "xterm-256color"

[window]
padding = { x = 16, y = 16 }
# Optional: make padding scale with DPI
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 30


[font]
size = 12

normal = { family = "NotoSansM Nerd Font Mono", style = "Regular" }
bold = { family = "NotoSansM Nerd Font Mono", style = "Bold" }
italic = { family = "NotoSansM Nerd Font Mono", style = "Italic" }
bold_italic = { family = "NotoSansM Nerd Font Mono", style = "Bold Italic" }
