# picom config
backend = "glx";
vsync = true;
use-damage = false;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-opacity = 0.45;

corner-radius = 14;
rules = (
	{ match = "class_g = 'Thunar'"; opacity = 0.92; },
	{ match = "class_g = 'st-256color'"; opacity = 0.9; },
	{ match = "class_g = 'dwm'"; opacity = 0.9; corner-radius = 5;},

 	{ match = "class_g = 'Google-chrome'"; clip-shadow-above = true; opacity = 1;},
 	{ match = "class_g = 'SpeedCrunch'"; corner-radius = 0;},
 	{ match = "class_g = 'Rofi'"; corner-radius = 0;},

  # no rounded corners
  { match = "window_type = 'menu'"; corner-radius = 0;},
  { match = "window_type = 'dropdown_menu'"; corner-radius = 0;},
  { match = "window_type = 'popup_menu'"; corner-radius = 0;},
  { match = "window_type = 'tooltip'"; corner-radius = 0;},
  { match = "window_type = 'combo'"; corner-radius = 0;},

  { match = "fullscreen"; corner-radius = 0;},

)

animations = (
  {
    triggers = ["close","hide"];
    preset = "disappear";
    scale = 0.7;
    duration = 0.1;
  },
  {
    triggers = ["open","show"];
    preset = "appear";
    scale = 0.7;
    duration = 0.1;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.18;
  }
)

