context.objects = [
  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = "from-desktop"
      media.class = Audio/Sink
      object.linger = true
      monitor.channel-volumes = true
      node.passive     = true
      audio.position = [ FL FR ]
    }
  }

  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = "from-caller"
      media.class = Audio/Sink
      object.linger = true
      monitor.channel-volumes = true
      node.passive     = true
      audio.position = [ FL FR ]
    }
  }

  {
    factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = "alsa_output.dummy-sink"
      media.class = Audio/Sink
      object.linger = true
      node.passive = true
      audio.position = [ FL FR ]
    }
  }

  {
    factory = adapter
    args = {
        factory.name     = support.null-audio-sink
        node.name        = "mic01-processed"
        media.class      = Audio/Source/Virtual
        object.linger    = true
        audio.position   = [ MONO ]
    }
  }

  {
    factory = adapter
    args = {
        factory.name     = support.null-audio-sink
        node.name        = "mic02-processed"
        media.class      = Audio/Source/Virtual
        object.linger    = true
        audio.position   = [ MONO ]
    }
  }

  {
    factory = adapter
    args = {
        factory.name     = support.null-audio-sink
        node.name        = "to-caller"
        media.class      = Audio/Source/Virtual
        object.linger    = true
        audio.position   = [ FL FR ]
    }
  }

  {
    factory = adapter
    args = {
        factory.name     = support.null-audio-sink
        node.name        = "alsa_input.dummy-source"
        media.class      = Audio/Source/Virtual
        object.linger    = true
        audio.position   = [ FL FR ]
    }
  }

]
