export HOSTNAME="alain-dm"
export TARGET_USERNAME="alain_pham_grafana_com"
export TARGET_USEREMAIL="alain.pham@grafana.com"
export KEYBOARD_LAYOUT="fr"
export KEYBOARD_MODEL="pc105"
export KEYBOARD_VARIANT="azerty"
export WILDCARD_DOMAIN="houze.dns.army"
export K3S_WILDCARD_DOMAIN="kubes.dns.army"
export DISABLE_TURBO_BOOST="false"
export NUMLOCK_ON_BOOT="true"
export AUTOMATIC_LOGIN="true"

export ENABLE_DEV="true"
export ENABLE_CONTAINERS="true"
export ENABLE_VIRTUALIZATION="false"
export ENABLE_DWM="false"
export ENABLE_STARTX="false"
export ENABLE_PICOM="false"
export ENABLE_GUI="false"
export ENABLE_WORKSTATION="false"
export ENABLE_GAMING="false"
export ENABLE_GAMING_EX="false"

export SUNSHINE_ON_BOOT="false"
