export HOSTNAME="ostw"
export TARGET_USERNAME="user"
export TARGET_USEREMAIL="user@localhost"
export KEYBOARD_LAYOUT="fr"
export KEYBOARD_MODEL="pc105"
export KEYBOARD_VARIANT="azerty"
export WILDCARD_DOMAIN="houze.dns.army"
export K3S_WILDCARD_DOMAIN="kubes.dns.army"
export DISABLE_TURBO_BOOST="false"
export NUMLOCK_ON_BOOT="true"
export AUTOMATIC_LOGIN="true"

export ENABLE_DEV="true"
export ENABLE_DEVAI="true"
export ENABLE_CONTAINERS="true"
export ENABLE_VIRTUALIZATION="true"
export ENABLE_DWM="true"
export ENABLE_STARTX="true"
export ENABLE_PICOM="true"
export ENABLE_GUI="true"
export ENABLE_WORKSTATION="true"
export ENABLE_GAMING="true"
export ENABLE_GAMING_EX="true"

export SUNSHINE_ON_BOOT="true"
